### ISSUE TITLE
How can I obtain the datasets?

### ISSUE THREAD

**Issue by betairylia** [lijin118/ATM#2]
e.g. when I want to run `python train_svhnmnist.py --mdd_weight 0.01 --epochs 50`, following error occurs:

```
Traceback (most recent call last):
  File "train_svhnmnist.py", line 211, in <module>
    main()
  File "train_svhnmnist.py", line 156, in main
    ImageList(open(source_list).readlines(), transform=transforms.Compose([
FileNotFoundError: [Errno 2] No such file or directory: 'data/svhn2mnist/svhn_balanced.txt'
```

I assume that I need to download the dataset in your required format. However you did not provide such dataset under `data/`, how can I run the program?
Could you tell me what should I do if I'd like to reproduce your results?
Thanks in advance.

**Comment by betairylia** [comment]
Just have found out:

* Unzip `data/data.zip` so you have `ROOT/data/svhn2mnist/` etc.
* Copy e.g. `data/svhn2mnist/svhn2mnist_dataset.py` to `data/` and run it. You may want to modify the code with `download=True`, also modify the MNIST test set part so it uses `torchvision.datasets.MNIST` with `train=False` instead of a hard-coded path.
* Perhaps you also need to modify e.g. `label_file.write('{:d}.png {:d}\n'.format(i, mnist_dataset.train_labels[i]))` so the path could meet the actual path?

And I got stuck at here since the training code are trying to load from `svhn_balanced.txt` but what I got so far was only `svhn.txt`. I am not sure that how should I generate the balanced dataset (without additional code).  
`FileNotFoundError: [Errno 2] No such file or directory: '/media/cep/HH/data/CDAN/svhn2mnist/svhn_image/3214.png'`  

Also I guess this method doesn't work for amazon datasets? At least I didn't found corresponding scripts.

Maybe you should mention this in your README ...
